//
//  P1332.m
//  DS
//
//  Created by Kiruthika on 29/03/20.
//  Copyright © 2020 Kiruthika Selvavinayagam. All rights reserved.
//
//
//https://leetcode.com/problems/remove-palindromic-subsequences/
//Given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.
//
//Return the minimum number of steps to make the given string empty.
//
//A string is a subsequence of a given string, if it is generated by deleting some characters of a given string without changing its order.
//
//A string is called palindrome if is one that reads the same backward as well as forward.
//
//
//
//Example 1:
//
//Input: s = "ababa"
//Output: 1
//Explanation: String is already palindrome
//Example 2:
//
//Input: s = "abb"
//Output: 2
//Explanation: "abb" -> "bb" -> "".
//Remove palindromic subsequence "a" then "bb".
//Example 3:
//
//Input: s = "baabb"
//Output: 2
//Explanation: "baabb" -> "b" -> "".
//Remove palindromic subsequence "baab" then "b".
//Example 4:
//
//Input: s = ""
//Output: 0
//
//
//Constraints:
//
//0 <= s.length <= 1000
//s only consists of letters 'a' and 'b'

#import "P1332.h"

@implementation P1332

- (BOOL)isPalindrome:(NSString *)str
{
    for (NSInteger i = 0, j = str.length - 1; i < j;)
    {
        char charI = [str characterAtIndex:i];
        char charJ = [str characterAtIndex:j];
        
        
        if([NSString stringWithFormat:@"%c", charI].lowercaseString != [NSString stringWithFormat:@"%c", charJ].lowercaseString)
        {
            return NO;
        }
        else
        {
            i++;
            j--;
        }
    }
    return YES;
}
- (NSInteger)removePalindromeSub:(NSString *)s
{
    if(s.length == 0)
    {
        return 0;
    }
    else if([self isPalindrome:s])
    {
        return 1;
    }
    return 2;
}

+ (void)solution
{
    P1332 *case1 = [[P1332 alloc] init];
    NSLog(@"%ld", (long)[case1 removePalindromeSub:@"ababa"]);
    NSLog(@"%ld", (long)[case1 removePalindromeSub:@"abb"]);
    NSLog(@"%ld", (long)[case1 removePalindromeSub:@"baabb"]);
    NSLog(@"%ld", (long)[case1 removePalindromeSub:@""]);
}
@end
